/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author James
 */
public class EnigmaFrame extends javax.swing.JFrame {

    /**
     * Creates new form EnigmaFrame
     */
    EnigmaModel _eModel;

    public EnigmaFrame() {
        _eModel = new EnigmaModel(1,2,3,1);
        initComponents();
        r3Setting.setText(Integer.toString(1));
        r2Setting.setText(Integer.toString(1));
        r1Setting.setText(Integer.toString(1));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        letterToEncode = new javax.swing.JLabel();
        encodeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        encodeBox = new javax.swing.JTextField();
        r3Text = new javax.swing.JLabel();
        r2Text = new javax.swing.JLabel();
        r1Text = new javax.swing.JLabel();
        reflectorText = new javax.swing.JLabel();
        refBox = new javax.swing.JComboBox<>();
        r3Box = new javax.swing.JComboBox<>();
        r2Box = new javax.swing.JComboBox<>();
        r1Box = new javax.swing.JComboBox<>();
        result = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultBox = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentWordBox = new javax.swing.JTextPane();
        currentWord = new javax.swing.JLabel();
        resetWord = new javax.swing.JButton();
        rotorSettings = new javax.swing.JLabel();
        r3Setting = new javax.swing.JTextField();
        r2Setting = new javax.swing.JTextField();
        r1Setting = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        encryptedWord = new javax.swing.JTextPane();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Rotor 3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        letterToEncode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        letterToEncode.setText("Letter to Encode");

        encodeButton.setText("Encode");
        encodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encodeButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Enigma Machine");

        r3Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r3Text.setText("Rotor 3");

        r2Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r2Text.setText("Rotor 2");

        r1Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r1Text.setText("Rotor 1");

        reflectorText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reflectorText.setText("Reflector");

        refBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reflector A", "Reflector B", "Reflector C" }));
        refBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refBoxActionPerformed(evt);
            }
        });

        r3Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V" }));
        r3Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3BoxActionPerformed(evt);
            }
        });

        r2Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V" }));
        r2Box.setSelectedIndex(1);
        r2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2BoxActionPerformed(evt);
            }
        });

        r1Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V" }));
        r1Box.setSelectedIndex(2);
        r1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1BoxActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        result.setText("Result");

        jScrollPane1.setViewportView(resultBox);

        jScrollPane2.setViewportView(currentWordBox);

        currentWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        currentWord.setText("Current Word");

        resetWord.setText("Reset Word");
        resetWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetWordActionPerformed(evt);
            }
        });

        rotorSettings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rotorSettings.setText("Rotor Settings");

        r3Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3SettingActionPerformed(evt);
            }
        });

        r2Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2SettingActionPerformed(evt);
            }
        });

        r1Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1SettingActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(encryptedWord);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(140, 140, 140))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rotorSettings)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(refBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(reflectorText)))
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(r3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(r3Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(r3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(61, 61, 61)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(r2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(r2Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addGap(10, 10, 10)
                                                                        .addComponent(r2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(54, 54, 54)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(r1Box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(r1Setting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(r1Text)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(encodeButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(82, 82, 82)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(62, 62, 62)
                                                                                .addComponent(currentWord))
                                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(letterToEncode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(encodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(176, 176, 176)
                                                                                .addComponent(result))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(137, 137, 137)
                                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(228, 228, 228)
                                                .addComponent(resetWord)))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(r1Text)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(r2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(r1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(r2Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(r1Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(r2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(r3Text)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(r3Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(r3Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(reflectorText)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(refBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rotorSettings)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(letterToEncode)
                                        .addComponent(result))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(encodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(encodeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentWord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetWord)
                                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>


    private void setRotor(String rotorSelection,int rotorNumber){
        if(rotorSelection.equals("I")){
            _eModel.changeRotor(rotorNumber,1);
        }else if(rotorSelection.equals("II")){
            _eModel.changeRotor(rotorNumber,2);
        }else if(rotorSelection.equals("III")){
            _eModel.changeRotor(rotorNumber,3);
        }else if(rotorSelection.equals("IV")){
            _eModel.changeRotor(rotorNumber,4);
        }else if(rotorSelection.equals("V")){
            _eModel.changeRotor(rotorNumber,5);
        }
    }

    private void refBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String currentValue = (String)refBox.getSelectedItem();
        if(currentValue.equals("Reflector A")){
            _eModel.setReflector(1);
        }else if(currentValue.equals("Reflector B")){
            _eModel.setReflector(2);
        }else if(currentValue.equals("Reflector C")){
            _eModel.setReflector(3);
        }
    }


    private void r1BoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String currentValue = (String)r1Box.getSelectedItem();
        setRotor(currentValue,1);
        r1Setting.setText(Integer.toString(1));

    }

    private void r2BoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String currentValue = (String)r1Box.getSelectedItem();
        setRotor(currentValue,2);
        r2Setting.setText(Integer.toString(1));
    }

    private void r3BoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String currentValue = (String)r1Box.getSelectedItem();
        setRotor(currentValue,3);
        r3Setting.setText(Integer.toString(1));
    }




    private void r1SettingActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        _eModel.setRotorValue(1,Integer.parseInt(r1Setting.getText()));
    }

    private void r2SettingActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        _eModel.setRotorValue(2,Integer.parseInt(r2Setting.getText()));
    }

    private void r3SettingActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        _eModel.setRotorValue(3,Integer.parseInt(r3Setting.getText()));
    }





    private void encodeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String text = encodeBox.getText();
        text = text.toUpperCase();
        char[] c = text.toCharArray();
        resultBox.setText(Character.toString(_eModel.addLetter(c[0])));
        currentWordBox.setText(_eModel.getCurrentWord());
        encryptedWord.setText(_eModel.getCurrentEncryptedWord());
        encodeBox.setText("");
        int[] rotorSetting = _eModel.getRotorSetting();
        r3Setting.setText(Integer.toString(rotorSetting[2]));
        r2Setting.setText(Integer.toString(rotorSetting[1]));
        r1Setting.setText(Integer.toString(rotorSetting[0]));
    }

    private void resetWordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        _eModel.resetWord();
        currentWordBox.setText("");
        encryptedWord.setText("");
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel currentWord;
    private javax.swing.JTextPane currentWordBox;
    private javax.swing.JTextField encodeBox;
    private javax.swing.JButton encodeButton;
    private javax.swing.JTextPane encryptedWord;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel letterToEncode;
    private javax.swing.JComboBox<String> r1Box;
    private javax.swing.JTextField r1Setting;
    private javax.swing.JLabel r1Text;
    private javax.swing.JComboBox<String> r2Box;
    private javax.swing.JTextField r2Setting;
    private javax.swing.JLabel r2Text;
    private javax.swing.JComboBox<String> r3Box;
    private javax.swing.JTextField r3Setting;
    private javax.swing.JLabel r3Text;
    private javax.swing.JComboBox<String> refBox;
    private javax.swing.JLabel reflectorText;
    private javax.swing.JButton resetWord;
    private javax.swing.JLabel result;
    private javax.swing.JTextPane resultBox;
    private javax.swing.JLabel rotorSettings;
    // End of variables declaration
}
